import 'dotenv/config';
import mongoose from 'mongoose';
import { connectDB } from '../config/database.js';
import { Carrera } from '../models/Carrera.js';

const CARRERAS = [
  {
    slug: 'ing-sistemas',
    nombre: 'Ingeniería de Sistemas',
    tipo: 'Universitaria',
    duracion: '10 semestres',
    categoria: 'tech',
    ematch: ['I', 'C', 'R'],
    intereses: ['tech', 'ingenieria'],
    resumen:
      'Diseñar software, sistemas y soluciones digitales. Una de las carreras con mayor demanda y posibilidad de trabajo remoto internacional desde cualquier rincón del país.',
    salarioEntrada: 3200000,
    salarioMedio: 6800000,
    salarioAlto: 14000000,
    empleabilidad: 92,
    demanda: 'Muy alta',
    costoSemestre: 8500000,
    becasICETEX: true,
    regionesDemanda: ['andina', 'caribe'],
    demandaPorRegion: { andina: 95, caribe: 78, pacifico: 55, orinoquia: 48, amazonia: 30, insular: 35 },
    universidades: [
      { nombre: 'Universidad Nacional', ciudad: 'Bogotá', publica: true, costoSem: 600000, ranking: 1 },
      { nombre: 'EAFIT', ciudad: 'Medellín', publica: false, costoSem: 11200000, ranking: 3 },
      { nombre: 'Universidad del Valle', ciudad: 'Cali', publica: true, costoSem: 750000, ranking: 5 },
      { nombre: 'UIS', ciudad: 'Bucaramanga', publica: true, costoSem: 520000, ranking: 4 },
    ],
    stayVsLeave: {
      stay: 'La demanda local por desarrolladores ha crecido 34% en tu región. Startups y bancos están contratando activamente.',
      leave: 'Medellín y Bogotá concentran el 68% de las vacantes senior y ofrecen hasta 2.3x tu salario local esperado.',
    },
    proyeccion2030: '+48% de vacantes',
  },
  {
    slug: 'medicina',
    nombre: 'Medicina',
    tipo: 'Universitaria',
    duracion: '12 semestres + rural',
    categoria: 'salud',
    ematch: ['S', 'I'],
    intereses: ['salud', 'social'],
    resumen:
      'Diagnosticar, tratar y acompañar personas. Impacto directo en tu comunidad, alta vocación social y una ruta larga pero estable.',
    salarioEntrada: 3900000,
    salarioMedio: 8200000,
    salarioAlto: 22000000,
    empleabilidad: 96,
    demanda: 'Alta',
    costoSemestre: 14500000,
    becasICETEX: true,
    regionesDemanda: ['pacifico', 'amazonia', 'caribe'],
    demandaPorRegion: { andina: 72, caribe: 88, pacifico: 94, orinoquia: 82, amazonia: 95, insular: 78 },
    universidades: [
      { nombre: 'Universidad de Antioquia', ciudad: 'Medellín', publica: true, costoSem: 580000, ranking: 1 },
      { nombre: 'Javeriana', ciudad: 'Bogotá', publica: false, costoSem: 18500000, ranking: 2 },
      { nombre: 'Universidad del Norte', ciudad: 'Barranquilla', publica: false, costoSem: 14800000, ranking: 4 },
    ],
    stayVsLeave: {
      stay: 'Las regiones apartadas pagan bonificaciones rurales de hasta 40% y ofrecen plazas inmediatas al graduarte.',
      leave: 'Especializarte en Bogotá o Medellín abre subespecialidades y sector privado de alto salario.',
    },
    proyeccion2030: '+22% de vacantes',
  },
  {
    slug: 'agronomia',
    nombre: 'Ingeniería Agronómica',
    tipo: 'Universitaria',
    duracion: '10 semestres',
    categoria: 'agro',
    ematch: ['R', 'I', 'C'],
    intereses: ['agro', 'ambiente'],
    resumen:
      'Producción sostenible, cultivos, suelos y cadenas agroalimentarias. Una carrera con fuerte arraigo territorial y creciente relevancia climática.',
    salarioEntrada: 2600000,
    salarioMedio: 4800000,
    salarioAlto: 9500000,
    empleabilidad: 84,
    demanda: 'Alta',
    costoSemestre: 3200000,
    becasICETEX: true,
    regionesDemanda: ['orinoquia', 'caribe', 'andina'],
    demandaPorRegion: { andina: 75, caribe: 85, pacifico: 70, orinoquia: 95, amazonia: 72, insular: 40 },
    universidades: [
      { nombre: 'Universidad Nacional (Palmira)', ciudad: 'Palmira', publica: true, costoSem: 450000, ranking: 1 },
      { nombre: 'Universidad de los Llanos', ciudad: 'Villavicencio', publica: true, costoSem: 520000, ranking: 3 },
      { nombre: 'UniMagdalena', ciudad: 'Santa Marta', publica: true, costoSem: 580000, ranking: 5 },
    ],
    stayVsLeave: {
      stay: 'Tu región productora necesita agrónomos con conocimiento local. Sueldos competitivos + vivienda incluida en fincas.',
      leave: 'ONGs, agroindustrias y cooperación internacional contratan en ciudades principales con salarios 30% mayores.',
    },
    proyeccion2030: '+31% de vacantes',
  },
  {
    slug: 'diseno-grafico',
    nombre: 'Diseño Gráfico',
    tipo: 'Universitaria',
    duracion: '8 semestres',
    categoria: 'arte',
    ematch: ['A', 'E'],
    intereses: ['arte', 'comunicacion', 'tech'],
    resumen:
      'Resolver problemas visuales: marcas, editorial, digital. Carrera creativa con alta posibilidad de freelance e ingresos internacionales.',
    salarioEntrada: 2100000,
    salarioMedio: 4200000,
    salarioAlto: 11000000,
    empleabilidad: 78,
    demanda: 'Media-alta',
    costoSemestre: 7800000,
    becasICETEX: true,
    regionesDemanda: ['andina', 'caribe'],
    demandaPorRegion: { andina: 92, caribe: 72, pacifico: 55, orinoquia: 42, amazonia: 25, insular: 48 },
    universidades: [
      { nombre: 'Universidad Nacional', ciudad: 'Bogotá', publica: true, costoSem: 620000, ranking: 1 },
      { nombre: 'Pontificia Bolivariana', ciudad: 'Medellín', publica: false, costoSem: 9200000, ranking: 2 },
      { nombre: 'Universidad Jorge Tadeo Lozano', ciudad: 'Bogotá', publica: false, costoSem: 10500000, ranking: 3 },
    ],
    stayVsLeave: {
      stay: 'El trabajo remoto para clientes internacionales se hace desde cualquier ciudad. No necesitas mudarte.',
      leave: 'Las grandes agencias y estudios están concentrados en Bogotá y Medellín con salarios y portafolios superiores.',
    },
    proyeccion2030: '+18% de vacantes',
  },
  {
    slug: 'admon-empresas',
    nombre: 'Administración de Empresas',
    tipo: 'Universitaria',
    duracion: '8 semestres',
    categoria: 'negocios',
    ematch: ['E', 'C', 'S'],
    intereses: ['negocios'],
    resumen:
      'Gestión, finanzas, operaciones, marketing. Una carrera versátil, empleable en casi cualquier sector y con fuerte tejido empresarial colombiano.',
    salarioEntrada: 2400000,
    salarioMedio: 5500000,
    salarioAlto: 18000000,
    empleabilidad: 88,
    demanda: 'Muy alta',
    costoSemestre: 6800000,
    becasICETEX: true,
    regionesDemanda: ['andina', 'caribe', 'pacifico'],
    demandaPorRegion: { andina: 92, caribe: 85, pacifico: 80, orinoquia: 65, amazonia: 40, insular: 55 },
    universidades: [
      { nombre: 'Universidad de los Andes', ciudad: 'Bogotá', publica: false, costoSem: 19200000, ranking: 1 },
      { nombre: 'ICESI', ciudad: 'Cali', publica: false, costoSem: 11800000, ranking: 3 },
      { nombre: 'Universidad del Norte', ciudad: 'Barranquilla', publica: false, costoSem: 12500000, ranking: 4 },
    ],
    stayVsLeave: {
      stay: 'El tejido empresarial regional necesita administradores con conocimiento del contexto. Emprender desde casa es viable.',
      leave: 'Multinacionales y banca concentran posiciones senior en capitales regionales.',
    },
    proyeccion2030: '+12% de vacantes',
  },
  {
    slug: 'psicologia',
    nombre: 'Psicología',
    tipo: 'Universitaria',
    duracion: '10 semestres',
    categoria: 'salud',
    ematch: ['S', 'I', 'A'],
    intereses: ['salud', 'social', 'educacion'],
    resumen:
      'Acompañar el bienestar mental individual y colectivo. Crece la demanda en salud pública, educación y sector corporativo.',
    salarioEntrada: 2300000,
    salarioMedio: 4600000,
    salarioAlto: 10500000,
    empleabilidad: 82,
    demanda: 'Alta',
    costoSemestre: 5200000,
    becasICETEX: true,
    regionesDemanda: ['andina', 'pacifico', 'caribe'],
    demandaPorRegion: { andina: 88, caribe: 82, pacifico: 85, orinoquia: 70, amazonia: 68, insular: 55 },
    universidades: [
      { nombre: 'Universidad Nacional', ciudad: 'Bogotá', publica: true, costoSem: 600000, ranking: 1 },
      { nombre: 'Pontificia Bolivariana', ciudad: 'Medellín', publica: false, costoSem: 8400000, ranking: 3 },
    ],
    stayVsLeave: {
      stay: 'El enfoque comunitario y las EPS locales contratan psicólogos con conocimiento cultural de la región.',
      leave: 'Consulta privada, corporate y trabajo clínico de alto nivel están en las ciudades grandes.',
    },
    proyeccion2030: '+38% de vacantes',
  },
  {
    slug: 'tec-desarrollo',
    nombre: 'Análisis y Desarrollo de Software',
    tipo: 'Tecnológica (SENA)',
    duracion: '6 semestres',
    categoria: 'tech',
    ematch: ['I', 'C'],
    intereses: ['tech'],
    resumen:
      'Ruta corta y gratuita al mundo del software. Con portafolio sólido compite con carreras largas en salarios iniciales.',
    salarioEntrada: 2400000,
    salarioMedio: 4800000,
    salarioAlto: 9500000,
    empleabilidad: 86,
    demanda: 'Muy alta',
    costoSemestre: 0,
    becasICETEX: false,
    regionesDemanda: ['andina', 'caribe', 'pacifico'],
    demandaPorRegion: { andina: 92, caribe: 78, pacifico: 72, orinoquia: 50, amazonia: 35, insular: 42 },
    universidades: [
      { nombre: 'SENA', ciudad: 'Nacional', publica: true, costoSem: 0, ranking: 1 },
      { nombre: 'Politécnico Grancolombiano', ciudad: 'Bogotá', publica: false, costoSem: 4200000, ranking: 3 },
    ],
    stayVsLeave: {
      stay: 'El SENA está en casi todos los municipios. Empiezas trabajando remoto desde tu ciudad.',
      leave: 'Para escalar a roles senior conviene moverte donde está la comunidad tech.',
    },
    proyeccion2030: '+52% de vacantes',
  },
  {
    slug: 'ing-ambiental',
    nombre: 'Ingeniería Ambiental',
    tipo: 'Universitaria',
    duracion: '10 semestres',
    categoria: 'ambiente',
    ematch: ['I', 'R', 'S'],
    intereses: ['ambiente', 'agro', 'ingenieria'],
    resumen:
      'Diseñar soluciones frente a crisis climática: agua, residuos, energía. Carrera con fuerte proyección a 2030.',
    salarioEntrada: 2800000,
    salarioMedio: 5200000,
    salarioAlto: 11500000,
    empleabilidad: 80,
    demanda: 'Alta',
    costoSemestre: 6500000,
    becasICETEX: true,
    regionesDemanda: ['pacifico', 'amazonia', 'caribe', 'orinoquia'],
    demandaPorRegion: { andina: 72, caribe: 85, pacifico: 92, orinoquia: 88, amazonia: 95, insular: 80 },
    universidades: [
      { nombre: 'Universidad Javeriana', ciudad: 'Bogotá', publica: false, costoSem: 14800000, ranking: 1 },
      { nombre: 'Universidad de Antioquia', ciudad: 'Medellín', publica: true, costoSem: 580000, ranking: 2 },
      { nombre: 'UniMagdalena', ciudad: 'Santa Marta', publica: true, costoSem: 620000, ranking: 4 },
    ],
    stayVsLeave: {
      stay: 'Tu región tiene retos ambientales únicos (biodiversidad, minería, agua) y necesita ingenieros locales.',
      leave: 'Consultoras internacionales y ONGs grandes están en capitales con salarios competitivos.',
    },
    proyeccion2030: '+44% de vacantes',
  },
  {
    slug: 'derecho',
    nombre: 'Derecho',
    tipo: 'Universitaria',
    duracion: '10 semestres',
    categoria: 'justicia',
    ematch: ['E', 'S', 'C'],
    intereses: ['justicia', 'social'],
    resumen:
      'Leyes, justicia, políticas públicas, empresa. Carrera amplia con múltiples rutas: litigio, corporativo, academia, sector público.',
    salarioEntrada: 2600000,
    salarioMedio: 5400000,
    salarioAlto: 20000000,
    empleabilidad: 85,
    demanda: 'Media-alta',
    costoSemestre: 9500000,
    becasICETEX: true,
    regionesDemanda: ['andina'],
    demandaPorRegion: { andina: 92, caribe: 78, pacifico: 70, orinoquia: 62, amazonia: 58, insular: 50 },
    universidades: [
      { nombre: 'Universidad del Rosario', ciudad: 'Bogotá', publica: false, costoSem: 16500000, ranking: 1 },
      { nombre: 'Universidad Externado', ciudad: 'Bogotá', publica: false, costoSem: 13800000, ranking: 2 },
      { nombre: 'Universidad de Cartagena', ciudad: 'Cartagena', publica: true, costoSem: 680000, ranking: 5 },
    ],
    stayVsLeave: {
      stay: 'Hay nicho en derecho étnico, ambiental y territorial con gran impacto en tu región.',
      leave: 'Firmas grandes y Ramas del poder concentran posiciones de alto nivel en Bogotá.',
    },
    proyeccion2030: '+8% de vacantes',
  },
  {
    slug: 'comunicacion-social',
    nombre: 'Comunicación Social',
    tipo: 'Universitaria',
    duracion: '9 semestres',
    categoria: 'comunicacion',
    ematch: ['A', 'S', 'E'],
    intereses: ['comunicacion', 'arte'],
    resumen:
      'Contar historias, manejar narrativas, periodismo, marketing, medios digitales. Alta versatilidad y posibilidad de trabajo remoto.',
    salarioEntrada: 2100000,
    salarioMedio: 4200000,
    salarioAlto: 12000000,
    empleabilidad: 75,
    demanda: 'Media',
    costoSemestre: 7200000,
    becasICETEX: true,
    regionesDemanda: ['andina', 'caribe'],
    demandaPorRegion: { andina: 90, caribe: 75, pacifico: 58, orinoquia: 45, amazonia: 35, insular: 40 },
    universidades: [
      { nombre: 'Javeriana', ciudad: 'Bogotá', publica: false, costoSem: 16200000, ranking: 1 },
      { nombre: 'Universidad de Antioquia', ciudad: 'Medellín', publica: true, costoSem: 580000, ranking: 3 },
    ],
    stayVsLeave: {
      stay: 'Medios regionales y creación de contenido local son un nicho poco atendido y con crecimiento.',
      leave: 'Agencias, productoras y medios nacionales se concentran en Bogotá y Medellín.',
    },
    proyeccion2030: '+14% de vacantes',
  },
  {
    slug: 'enfermeria',
    nombre: 'Enfermería',
    tipo: 'Universitaria',
    duracion: '8 semestres',
    categoria: 'salud',
    ematch: ['S', 'R', 'C'],
    intereses: ['salud', 'social'],
    resumen:
      'Atención directa a pacientes, fuerte vocación social, empleabilidad casi garantizada en todo el país e incluso internacional.',
    salarioEntrada: 2400000,
    salarioMedio: 4400000,
    salarioAlto: 8500000,
    empleabilidad: 94,
    demanda: 'Muy alta',
    costoSemestre: 5400000,
    becasICETEX: true,
    regionesDemanda: ['pacifico', 'caribe', 'amazonia', 'andina'],
    demandaPorRegion: { andina: 88, caribe: 92, pacifico: 95, orinoquia: 88, amazonia: 94, insular: 85 },
    universidades: [
      { nombre: 'Universidad Nacional', ciudad: 'Bogotá', publica: true, costoSem: 560000, ranking: 1 },
      { nombre: 'UniValle', ciudad: 'Cali', publica: true, costoSem: 680000, ranking: 3 },
    ],
    stayVsLeave: {
      stay: 'Hospitales y clínicas en todo el país contratan enfermería. Te quedas cerca de tu familia con trabajo estable.',
      leave: 'Opción de migrar a España, Canadá o EE.UU. con homologación; salarios 4-6x.',
    },
    proyeccion2030: '+36% de vacantes',
  },
  {
    slug: 'tec-mecatronica',
    nombre: 'Tecnología en Mecatrónica',
    tipo: 'Tecnológica',
    duracion: '6 semestres',
    categoria: 'ingenieria',
    ematch: ['R', 'I'],
    intereses: ['ingenieria', 'tech'],
    resumen:
      'Automatización industrial, electrónica, robótica. Alta empleabilidad en zonas con industria manufacturera y energía.',
    salarioEntrada: 2600000,
    salarioMedio: 4800000,
    salarioAlto: 9000000,
    empleabilidad: 88,
    demanda: 'Alta',
    costoSemestre: 1800000,
    becasICETEX: true,
    regionesDemanda: ['andina', 'caribe', 'orinoquia'],
    demandaPorRegion: { andina: 90, caribe: 82, pacifico: 60, orinoquia: 80, amazonia: 35, insular: 30 },
    universidades: [
      { nombre: 'SENA', ciudad: 'Nacional', publica: true, costoSem: 0, ranking: 1 },
      { nombre: 'Politécnico Jaime Isaza Cadavid', ciudad: 'Medellín', publica: true, costoSem: 980000, ranking: 3 },
    ],
    stayVsLeave: {
      stay: 'Parques industriales y zonas francas cerca contratan tecnólogos sin exigir mudanza.',
      leave: 'Medellín y Bogotá tienen ecosistemas manufactureros más complejos y mejores salarios senior.',
    },
    proyeccion2030: '+28% de vacantes',
  },
];

async function seed() {
  await connectDB();
  await Carrera.deleteMany({});
  const inserted = await Carrera.insertMany(CARRERAS);
  console.log(`✅  Seeded ${inserted.length} carreras`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
